# -*- coding: utf-8 -*-

DB = 'huobipro.db'

ACCKEY = "451ea17c-77ed704a-f3ferfref-af477"
SECKEY = "6204fb72-bde5858c-57reffr0b-deba4"

#QTUM
QTUMSYMBOL = 'QTUM/USDT'
QTUMTABLE = 't_qtum_order'
QTUMAMOUNT = 0.1
QTUMPERCENT = 15

#EOS
EOSSYMBOL = 'EOS/USDT'
EOSTABLE = 't_eos_order'
EOSAMOUNT = 0.1
EOSPERCENT = 15

#NEO
NEOSYMBOL = 'NEO/USDT'
NEOTABLE = 't_neo_order'
NEOAMOUNT = 0.1
NEOPERCENT = 15

#ETH
ETHSYMBOL = 'ETH/USDT'
ETHTABLE = 't_eth_order'
ETHAMOUNT = 1
ETHPERCENT = 5

#XRP
XRPSYMBOL = 'ETH/USDT'
XRPTABLE = 't_xrp_order'
XRPAMOUNT = 1
XRPPERCENT = 5

BUYHOUR='*/23'
BUYMINUTE='0'

SELLHOUR='*'
SELLMINUTE='*/5'

HARDBUYHOUR='*/23'
HARDBUYMINUTE='0'
